#!/bin/bash
echo " "
echo "🚀 GITOPS ACCESS DASHBOARD"
echo "=========================="
echo " "

echo "🌐 INGRESS ACCESS (RECOMMENDED)"
echo "Staging:    http://localhost/staging"
echo "Production: http://localhost/production"
echo " "
echo "🏠 HOST-BASED ACCESS"
echo "Staging:    http://staging.localhost"
echo "Production: http://production.localhost"
echo " "
echo "🔌 PORT FORWARDING"
echo "Staging:    http://localhost:28081"
echo "Production: http://localhost:28082"
echo " "
echo "📊 ARGOCD DASHBOARD"
echo "URL: https://localhost:8443"
echo "User: admin"
echo "Pass: rSVJOukurphWN40G"
echo " "
echo "🐙 GITHUB REPOSITORY"
echo "URL: https://github.com/nanado002/devsecops-gitops-demo"
echo "Actions: https://github.com/nanado002/devsecops-gitops-demo/actions"
echo " "
echo "✅ Your applications are accessible via multiple methods!"
echo "   The Ingress method is recommended for production use."
