apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tic-tac-toe-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nanado002/devsecops-gitops-demo.git
    targetRevision: HEAD
    path: gitops/environments/production
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
