apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

replicas:
  - name: tic-tac-toe
    count: 3

commonLabels:
  environment: production
